### ISSUE TITLE
Add geospatial data in tabular form

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/datacommon#68]
The current databrowser app doesn't load the geospatial data, it only loads the tabular. We do not have a way to integrate the data into the app because we are missing its manifest table which  describes how to categorize and link to the geospatial tables. 

This issue will be fixed when the geospatial data is categorized in the topic/subtopic lists, viewable in tabular form, and downloadable.

- [x] Load in geospatial topic/subtopics (#69)
- [x] View geospatial data in tabular form (#70)
- [x] Load in geospatial metadata (#71)
- [x] Download geospatial data/metadata (#72)
